services:
  backend:
    image: docker-manager-backend:prod-build
    container_name: docker-manager-backend
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_UI_DB_PATH=/data/app.db
    ports:
      - "8080:8080"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ../:/root/stsbmt:ro
      - backend_data:/data
    restart: always

  frontend:
    image: docker-manager-frontend:prod-build
    container_name: docker-manager-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  backend_data:
